export const CREATE_NEW_PAGE = 'CREATE_NEW_PAGE';

export const REQUEST_STORE_LIST = 'REQUEST_STORE_LIST';
export const GET_STORE_LIST_SUCCESS = 'GET_STORE_LIST_SUCCESS';
export const GET_STORE_LIST_FAIL = 'GET_STORE_LIST_FAIL';

export const REQUEST_GUEST_TOKEN = 'REQUEST_GUEST_TOKEN';
export const SUCCESS_GUEST_TOKEN = 'SUCCESS_GUEST_TOKEN';
export const FAIL_GUEST_TOKEN = 'FAIL_GUEST_TOKEN';
