export const CREATE_NEW_PAGE = 'CREATE_NEW_PAGE';

export const REQUEST_STORE_LIST = 'REQUEST_STORE_LIST';
export const GET_STORE_LIST_SUCCESS = 'GET_STORE_LIST_SUCCESS';
export const GET_STORE_LIST_FAIL = 'GET_STORE_LIST_FAIL';
